databases:
  - name: expensetracker
    databaseName: expensetracker
    user: expensetracker
    plan: free

services:
  - type: web
    name: expensetracker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
     startCommand: "./bin/rails server"

    # startCommand: "bundle exec rails server" # to test production issue
    envVars:
      - key: DATABASE_URL # to decrypt sensitive info using a master key
        fromDatabase:
          name: expensetracker
          property: connectionString
      - key: RAILS_MASTER_KEY # use it to decrypt sensitive info, e.g. credentials
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
